_BASE_: "../Base-RCNN-FPN-VCM.yaml"
MODEL:
  MASK_ON: True
#  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
#  WEIGHTS: "/media/data/ccr/VCM/output/model_mseP1.pth"
  WEIGHTS: "/media/data/ccr/model_final_2d9806.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
SOLVER:
  STEPS: (80000, 110000)
  MAX_ITER: 120000

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
#  MIN_SIZE_TRAIN: (32, 32)
#  MIN_SIZE_TRAIN: (576, 576)
#  MIN_SIZE_TRAIN: (416, 416)
#  MIN_SIZE_TRAIN: (352, 352)
#  MIN_SIZE_TEST: 576
  MIN_SIZE_TEST: 800
#  MIN_SIZE_TEST: 352